### ISSUE TITLE
Export to latex, many errors

### ISSUE THREAD

**Issue by edbird** [AlecAivazis/feynman#82] opened 2017-07-20 13:21 UTC
Errors include: error strokeWidth undefined. I have \usepackage{feynman} in my preamble, and the feynman.sty package in the root directory, where my document.tex file is located.

**Comment by AlecAivazis** [comment] 2017-07-20 16:49
Thanks for reporting this @edbird and i'm sorry for any inconveniences it's caused. I'm able to export the default DY pattern on my OSX a laptop. I suspect this is related to the other issue you submitted and there might be a bug in the latex package - can you paste the diagram code here?

**Comment by AlecAivazis** [comment] 2017-07-20 17:40
I am able to reproduce your issue by adding a custom width to a propagator, seems to confirm my th. Can you check if you are able to export the default `Drell-Yan` pattern? If you can, i think #81 can be closed.

**Comment by AlecAivazis** [comment] 2017-07-20 17:53
So the issue is that the latex package expects `lineWidth` not `strokeWidth`. This bug was caused during teh recent rewrite to React - i'll push a fix for this by the end of the day. You should be able to get your diagram to compile by making that change. Sorry again!

**Comment by AlecAivazis** [comment] 2017-07-20 22:12
@edbird i just published the fix and verified that I can export an image with a custom lineWidth on the application - you might have to clear your local browsing history to get the change.

**Comment by edbird** [comment] 2017-07-21 12:57
Hi Alec, I saw your updates yesterday evening but was away from work so I could not respond. The diagram code is:

\begin{feynman} 
    \fermion[]{0.20, 0.60}{9.80, 0.60}
    \fermion[]{0.20, 0.20}{9.80, 0.20}
    \fermion[]{0.20, 7.00}{9.80, 7.00}
    \fermion[label=$e$]{5.00, 3.00}{9.80, 3.00}
    \fermion[]{0.20, 7.40}{9.80, 7.40}
    \electroweak[strokeWidth=$2$, direction=$-1$, label=$W^-$, labelDistance=-0.70, labelLocation=0.00]{3.00, 6.60}{5.00, 4.60}
    \electroweak[label=$W^-$, labelDistance=1.20, labelLocation=0.00]{3.00, 1.00}{5.00, 3.00}
    \fermion[]{0.20, 1.00}{9.80, 1.00}
    \dashed[arrow=$0$]{5.00, 3.00}{5.00, 4.60}
    \fermion[label=$e$]{5.00, 4.60}{9.80, 4.60}
    \fermion[]{0.20, 6.60}{9.80, 6.60}
    \text{0.80,8.00}{n}
    \text{8.80,0.00}{p}
    \text{8.80,8.00}{p}
    \text{0.80,0.00}{n}
\end{feynman}

Can I save my diagram somehow so that I do not have to draw it again before clearing my browser?

**Comment by AlecAivazis** [comment] 2017-07-21 15:40
Ah yea I see two problems: your browser is using a cached version of the app

**Comment by AlecAivazis** [comment] 2017-07-22 16:21
The issue wtih the hidden arrow should now be fixed - let me know if you run into any more issues.

**Comment by edbird** [comment] 2017-07-25 12:44
Hi again,

Sorry it took me a few days to respond as I had other work I needed to do urgently.

I have tried running a test with the Drell-Yan diagram. Here is my tex file:

\documentclass{article}
\usepackage{feynman}
\begin{document}

    \begin{figure}
        \begin{feynman} 
            \fermion[label=$l$]{2.20, 2.20}{0.20, 4.20}
            \fermion[label=$\anti{l}$]{0.20, 0.20}{2.20, 2.20}
            \electroweak[color=2d89d3, label=$Z$]{2.20, 2.20}{5.20, 2.20}
            \fermion[label=$l$]{7.20, 4.20}{5.20, 2.20}
            \fermion[label=$\anti{l}$]{5.20, 2.20}{7.20, 0.20}
        \end{feynman}
    \end{figure}

\end{document}

I compiled this with texstudio, and the error I now encounter is \anti: Missing $ inserted. ...[label=$\anti{l}$]{0.20, 0.20}{2.20, 2.20}

If I remove the "anti" command and leave the label as an "l" then the file compiles.

Perhaps I should have raised this as a new issue?

I will now test the diagram I wanted originally.

**Comment by edbird** [comment] 2017-07-25 12:47
Here is what I could read from TexStudio output.

Package keyval Error: direction undefined. ...abelLocation=0.00]{3.00, 6.60}{5.00, 4.60}

Does this give any indication of the problem? If not, what can I do to help?

**Comment by AlecAivazis** [comment] 2017-07-26 01:56
Hmm so i was using the fact that I could export the drell-yan diagram to an image as proof that it would work using the latex package since the server renders the image using the code shown in the overlay that pops up when you export to latex.

Can you see if you can export it using the app? Also, can you try removing the `$` surrounding the anti command?

And the problem with your diagram is in the `direction` key, i'll fix that tonight. Sorry about all of this, thanks for being so patient!

**Comment by AlecAivazis** [comment] 2017-07-26 02:25
The problem with `direction` should now be fixed - please copy and paste the diagram from the web app and see if that works. You'll probably still run into the issue with `\anti`, looking into that now.

**Comment by edbird** [comment] 2017-07-26 14:15
Hi again - it's no problem, I appreciate the help.

In regards to the Drell-Yan diagram. The following seems to work:

        \begin{feynman} 
    		\fermion[label=l]{2.20, 2.20}{0.20, 4.20}
    		\fermion[label=\anti{l}]{0.20, 0.20}{2.20, 2.20}
    		\electroweak[color=2d89d3, label=$Z$]{2.20, 2.20}{5.20, 2.20}
    		\fermion[label=l]{7.20, 4.20}{5.20, 2.20}
    		\fermion[label=\anti{l}]{5.20, 2.20}{7.20, 0.20}
    	\end{feynman}

Note removal of all $ signs from the labels, including those without "anti".

The Feynman diagram (Drell-Yan) I generated online just a moment ago still contains the $ signs when I export. Does this mean I need to re-open my browser or something like that?

At the moment I have my more complicated double-beta decay diagram still open in a tab. Is there any way to save this diagram so that I don't have to re-create it if I refresh my browser or whatever I have to do to get the code updates/changes which you have made?

**Comment by AlecAivazis** [comment] 2017-07-28 23:08
@edbird, i haven't removed the `$` yet because I want to understand a little better why that is what's causing the problem. `anti` is just an alias for `overline` which AFAIK, needs to be wrapped in a math environment. I have a few different bugs to fix with the latex package so I'll try to get them taken care of by the end of the weekend. 

Also, I do not yet have a good solution for saving your work. This has been at the top of the feature list for a long while, i just needed a break after the lengthy rewrite but I will get back to adding more features this weekend, maybe I can sneak in an autosave feature as well. Question - would you prefer it to always auto-save or have another shortcut?

**Comment by AlecAivazis** [comment] 2017-07-29 22:00
@edbird I've been messing around the latex package all day and compiled many diagrams with `$` in labels. Here is the full extent of the code I am using to test my changes:
```latex
\documentclass[border=1pt]{standalone}

\usepackage{feynman}

\begin{document}

    \begin{feynman}
        \fermion[label=$\anti{l}$]{2.00, 2.00}{0.00, 4.00}
        \fermion[label=$\anti{l}$]{0.00, 0.00}{2.00, 2.00}
        \electroweak[color=2d89d3, label=$Z$]{2.00, 2.00}{5.00, 2.00}
        \fermion[label=$l$]{7.00, 4.00}{5.00, 2.00}
        \fermion[label=$\anti{l}$]{5.00, 2.00}{7.00, 0.00}
    \end{feynman}

\end{document}
```

Could you try this for me and see if it compiles? You might have to download the latest version of the latex package.

**Comment by edbird** [comment] 2017-07-31 12:41
@AlecAivazis I would probably prefer a way to save the file to disk (we already have that via export to latex) - but it would also be good to have a load from disk method. (Of course, this would be a problem if the standard / latex syntax changed...)

I got the new feynman.sty file direct from the github package you edited 2 days ago. (Feynman, not Feynman-old, which is still linked from your homepage here: http://alec.aivazis.com/projects/Feynman - the github link navigates to feynman-old - not sure if you knew this already?)

As for the example, I tried to compile it using texstudio... I get a lot of errors, the first one is:
Missing $ inserted. ...[label=$\anti{l}$]{2.00, 2.00}{0.00, 4.00}

So perhaps I did not get the right version for feynman.sty?

**Comment by AlecAivazis** [comment] 2018-02-26 03:46
@edbird were you ever able to fix your problems?

**Comment by edbird** [comment] 2018-03-01 10:46
Hi @AlecAivazis 

I've not needed to do any work which used the feynman package for a while, but I think I certainly will do in the future.

If I remember correctly I never got it fully working.

I might be able to test some stuff for you however if you make any changes.

I remember the main issue I was having was I could make the diagrams using your online tool, but when exporting them to tex, and compiling them in a tex document (using texstudio etc) I got a load of compile errors.

**Comment by AlecAivazis** [comment] 2018-03-04 19:21
Thanks for responding @edbird. Since there have been many fixes since your original issue, I would like to close this one and ask that you open another when you run into them again. Hopefully by the time you try again, I can fix what I suspect is your problem: i think the browser is caching the file when you download `feynman.sty` which is preventing you from getting the latest version.

**Closed by AlecAivazis** 2018-03-04 19:21 UTC

**Comment by edbird** [comment] 2018-03-04 19:29
Yes that's fine
