### ISSUE TITLE
Labeling

### ISSUE THREAD

**Issue by Kvothe-The-Bloodless** [AlecAivazis/feynman#89] opened 2017-11-13 11:01 UTC
Hi, I seem to fail utterly at labeling things. I use the text option as I don't see an explicit option to label at points, perhaps this is my mistake. Anyhow, the text can only be placed at discrete intervals which are too big. And the moving of the elements by dragging seems to just not even work on text at all. Are these major bugs or more likely am I using text in the wrong way?

**Comment by AlecAivazis** [comment] 2018-02-26 03:45
hey @Kvothe-The-Bloodless - sorry for taking so long to get back to you about these issues. I don't know why github didn't notify me about your message. 

I hadn't heard of anyone needed to label specific points but it definitely seems like a reasonable request. I'll work on something as soon as possible. 

I was able to test that dragging text works as expected on google chrome - what browser are you using?

**Comment by ksedgar** [comment] 2018-03-02 23:17
Hello Alec 
I am seeing the same issue. When I drag the text object to create a label, I dont see it anywhere on the canvas. Also, when I get the latex code after inserting a text label, I see: \text{NaN,NaN}{text!} 
Tried this on Firefox, Safari and Chrome. 
On Firefox and safari, I see the same issue. 
On Chrome, I can see the text label, but I cannot move it around on the canvas. 
Thanks for looking into whats going on!

**Comment by AlecAivazis** [comment] 2018-03-02 23:30
@ksedgar - thanks for reporting this. I"m going to try to get to the bottom of it this weekend. I have verified that labels in firefox don't work anymore. I"m assuming you are using the most update to date version of these browsers. Something has recently changed in firefox's support for embedding images in svg - I'll report more when I have more information. Same with safari so I suspect something was previously working that should. 

I just checked chrome and am able to drag labels around. I also do not see the `NaN` issue you are reporting on any of the browser. Can you tell me the version of chrome you are running? 

 Maybe you have a cached version of the app?  Can you try clearing your local cache and refreshing the page?

**Comment by AlecAivazis** [comment] 2018-03-02 23:48
Oh I was able to verify the issue  on chrome that you mentioned @ksedgar.

I was able move around element labels, but not text elements.

**Comment by ksedgar** [comment] 2018-03-03 00:33
Ok great! 
In case you still need my Chrome version, here it is: Version 64.0.3282.186 (Official Build) (64-bit).

**Comment by ksedgar** [comment] 2018-03-03 00:36
Also, take your time debugging. I am in no rush!

**Comment by AlecAivazis** [comment] 2018-03-04 19:07
@ksedgar @Kvothe-The-Bloodless: I figured out the issue with dragging text on a diagram - it should be deployed and available in a few minutes

I haven't added the feature for labeling an anchor, but I will get to that soon. In the meantime, you should be able to get away with labeling the propagator.

**Comment by ksedgar** [comment] 2018-03-05 01:36
Woohoo! All fixed in firefox as well! 
Thanks!

**Comment by Soureek89** [comment] 2018-06-16 06:39
Hi Alec,
I using the "Label" field for labeling the objects. The problem is that the default output label is not very sharp. Is there some feature to choose the font and font size for "Label" field? If not, can you please add a feature like this?

**Comment by AlecAivazis** [comment] 2018-06-16 16:45
Hey @Soureek89 - i'm sorry to hear that the images are not rendering crisply for you. Can you please take a screenshot so I can understand what you're seeing? 

Adding the ability to scale the font-size shouldn't be too hard but I don't think i'll have time to do it for a month or so. I am leaving for vacation next week and have a lot to do with work to get ready for that. I'll add a reminder to look into this when I get back - sorry for the delay!

**Comment by Soureek89** [comment] 2018-06-16 17:00
For example, in this diagram generated using the "feynman" package, the labels are not so sharp. I was wondering if it can be improved somehow.
<img width="720" alt="tch_5fs" src="https://user-images.githubusercontent.com/5044984/41500711-61b3578c-7197-11e8-9777-ca1955b89f24.png">

**Comment by AlecAivazis** [comment] 2018-07-05 14:40
@Soureek89 I see what you mean now - the text is pretty fuzzy. Are those rendered with the actual latex package or are they png's generated by the web application?

**Comment by Soureek89** [comment] 2018-07-05 17:16
@AlecAivazis: These images in my previous post is the png file generated by the web application. I also tried with the actual latex package. The problem is the following.
When I try to use the pdf image (generated by image tex file from your package) into my tex document, label font size is too small compared to the normal text font size in the final document pdf. I even tried with \HUGE for the label font size to make it bigger. Unfortunately, that does not work.

**Comment by AlecAivazis** [comment] 2018-07-05 17:20
@Soureek89 thanks for responding so quickly.

Do you mind opening another issue since this is a different problem than what was originally submitted? I am about to get onto a flight (in a few hours) so I want to make sure I have all of the necessary information to debug this in case I dont have network on the plane. 

That being said, could you also try again? I just pushed a fix which should drastically improve the rendering quality of the pngs that are returned by the application.

**Closed by AlecAivazis** 2018-07-05 17:20 UTC

**Comment by AlecAivazis** [comment] 2018-07-09 04:43
@Soureek89 - i also just added the ability to save as a PDF. Hopefully that address your fontsize issues.
